In [ ]:
import tensorflow as tf
import glob
from PIL import Image
import glob
import os
import cv2
import numpy as np

In [ ]:
tf.test.gpu_device_name()

'/device:GPU:0'

In [ ]:
# for picture ,n in zip(glob.glob('/content/drive/MyDrive/Image/*.png'), range(1,7)):
#     my_image= Image.open(picture)
#     for i in range(1,5):
#         rotated = my_image.rotate(i * 90)
#         rotated.save(f"/content/drive/MyDrive/IMage/test{n}{i}.png")

# for picture ,n in zip(glob.glob('/content/drive/MyDrive/IMage/*.png'), range(1,25)):
#     img= Image.open(picture)
#     img2=img.convert('RGBA')
#     for i in range(1,11):
#         rot = img2.rotate(i*36, expand=1)
# # a white image same size as rotated image
#         fff = Image.new('RGBA', rot.size, (255,)*4)
# # create a composite image using the alpha layer of rot as a mask
#         out = Image.composite(rot, fff, rot)
# # save your work (converting back to mode='1' or whatever..)
#         out.convert(img.mode).save(f"/content/drive/MyDrive/IMage/test{n}-t{i}.png")
        

In [ ]:
my_dataset=[]
label=[]


files = glob.glob ("/content/drive/MyDrive/IMage/circle/*png")
for myFile in files:
    image = cv2.imread(myFile)
    image.resize(100,100,1)
    my_dataset.append(image)

print(len(my_dataset))

files = glob.glob ("/content/drive/MyDrive/IMage/rectangle/*png")
for myFile in files:
    image = cv2.imread(myFile)
    image.resize(100,100,1)
    my_dataset.append(image)
    
print(len(my_dataset))

files = glob.glob ("/content/drive/MyDrive/IMage/triangle/*png")
for myFile in files:
    image = cv2.imread(myFile)
    image.resize(100,100,1)
    my_dataset.append(image)

print(len(my_dataset))



1144
2200
3432


In [ ]:
label=[[1,0,0] for i in range(1144)]+[[0,1,0] for i in range(1056)]+[[0,0,1] for i in range(1232)]

In [ ]:
Dataset=np.array(my_dataset)
Label=np.array(label)

In [ ]:
print(Dataset.shape)
print(Label.shape)

(3432, 100, 100, 1)
(3432, 3)


In [ ]:
Dataset = Dataset.reshape((3432, 100 * 100))
Dataset = Dataset.astype("float32") / 255


In [ ]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(128, activation="relu"),
    layers.Dense(64, activation="relu"),
    layers.Dense(16, activation="relu"),
    layers.Dense(3, activation="softmax"),
])
model.compile(optimizer="rmsprop",
              loss="categorical_crossentropy",
              metrics=["mse"])


In [ ]:
model.fit(Dataset, Label, epochs=10, verbose=2)

Epoch 1/10
108/108 - 3s - loss: 1.0987 - mse: 0.2222 - 3s/epoch - 30ms/step
Epoch 2/10
108/108 - 0s - loss: 1.0980 - mse: 0.2221 - 326ms/epoch - 3ms/step
Epoch 3/10
108/108 - 0s - loss: 1.0970 - mse: 0.2219 - 322ms/epoch - 3ms/step
Epoch 4/10
108/108 - 0s - loss: 1.0976 - mse: 0.2220 - 325ms/epoch - 3ms/step
Epoch 5/10
108/108 - 0s - loss: 1.0967 - mse: 0.2218 - 338ms/epoch - 3ms/step
Epoch 6/10
108/108 - 0s - loss: 1.0975 - mse: 0.2220 - 333ms/epoch - 3ms/step
Epoch 7/10
108/108 - 0s - loss: 1.0973 - mse: 0.2219 - 324ms/epoch - 3ms/step
Epoch 8/10
108/108 - 0s - loss: 1.0972 - mse: 0.2219 - 330ms/epoch - 3ms/step
Epoch 9/10
108/108 - 0s - loss: 1.0970 - mse: 0.2219 - 335ms/epoch - 3ms/step
Epoch 10/10
108/108 - 0s - loss: 1.0972 - mse: 0.2219 - 336ms/epoch - 3ms/step


In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               1280128   
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dense_2 (Dense)             (None, 16)                1040      
                                                                 
 dense_3 (Dense)             (None, 3)                 51        
                                                                 
Total params: 1,289,475
Trainable params: 1,289,475
Non-trainable params: 0
_________________________________________________________________


In [ ]:
test_image=[]
files = glob.glob ("/content/drive/MyDrive/IMage/*png")
for myFile in files:
    image = cv2.imread(myFile)
    image.resize(100,100,1)
    test_image.append(image)

In [ ]:
len(test_image)

270

In [ ]:
test_image= np.array(test_image)
test_image = test_image.reshape((270, 100 * 100))
test_image = test_image.astype("float32") / 255
test_image.shape

(270, 10000)

In [ ]:
p=model.predict(test_image)

9/9 [==============================] - 0s 2ms/step


In [ ]:
print(p[31:34])
p[31:34].argmax()

[[3.9237207e-06 9.0836545e-14 9.9999607e-01]
 [3.9237207e-06 9.0836545e-14 9.9999607e-01]
 [3.9237207e-06 9.0836545e-14 9.9999607e-01]]


2

In [ ]:
print(p[24])
p[24].argmax()

[4.2076340e-06 1.0750071e-13 9.9999583e-01]


2